import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/shared/header";
import Footers from "@/components/shared/footers";
import Chat from "@/components/shared/chat";

const tripSansRegular = localFont({
  src: "./fonts/TripSans-Regular.woff", // Ensure this path is correct
  variable: "--font-trip-sans-regular",
  weight: "400",
});

const tripSansBold = localFont({
  src: "./fonts/TripSans-Bold.woff", // Ensure this path is correct
  variable: "--font-trip-sans-bold",
  weight: "900",
});

const tripSansMedium = localFont({
  src: "./fonts/TripSans-Medium.woff", // Ensure this path is correct
  variable: "--font-trip-sans-medium",
  weight: "700",
});

export const metadata: Metadata = {
  title: "TripHive Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${tripSansRegular.variable} ${tripSansBold.variable} ${tripSansMedium.variable} antialiased`}
      >
        {/* Uncomment these components if you want them rendered */}
        <Header />
        {children}
        <Chat />
        <Footers />
      </body>
    </html>
  );
}
